name: GitHub Actions Example

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run GitHub API request
        run: |
          const { Octokit } = require('@octokit/rest');
          const octokit = new Octokit({
            auth: process.env.GH_TOKEN,
          });
          async function checkVersion() {
            const response = await octokit.request('GET /search/topics', {
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
            console.log(response.data);
          }
          checkVersion();
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub Secrets에서 가져온 토큰
